services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=produto
      - POSTGRES_PASSWORD=produto
      - POSTGRES_DB=produto
    volumes:
      - ./src/main/resources/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
