server:
    port: 8080
    servlet:
        context-path: /produto
spring:
    application:
        name: produto-api
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/produto
        username: produto
        password: produto
    jpa:
        generate-ddl: true
        show-sql: true
        properties:
          hibernate:
              format_sql: true

    flyway:
        enabled: false
        locations: classpath:db/migration